name: vpngate
on:
  repository_dispatch:
    types: [vpngate]
  workflow_dispatch:
jobs:
  vpngate:
    name: vpngate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ${{secrets.vpngate}}
      - run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ovpn.zip
          git commit -m "Update ovpn.zip"
          git push origin main --force
